[build-system]
requires = ["setuptools", "wheel", "bob.extension", "bob.blitz", "bob.core", "bob.io.base", "bob.sp", "bob.math", "bob.learn.activation", "bob.learn.linear"]
build-backend = "setuptools.build_meta"
