{% set data = load_file_data(RECIPE_DIR + '/../pyproject.toml') %}
{% set name = data['project']['name'] %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ data['project']['version'] }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    - "{{ PYTHON }} -m pip install . -vv"
    # installs the documentation source, readme to share/doc so it is available
    # during test time
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob.extension
    - numpy {{ numpy }}
    - dask {{ dask }}
    - dask-ml {{ dask_ml }}
    - h5py {{ h5py }}
    - h5py >=3
    - scikit-learn {{ scikit_learn }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - {{ pin_compatible('dask') }}
    - {{ pin_compatible('dask-ml') }}
    - {{ pin_compatible('h5py') }}
    # scikit-learn keeps breaking API in minor versions, so we pin to the
    # next minor version
    - {{ pin_compatible('scikit-learn', max_pin='x.x') }}

test:
  imports:
    - {{ name }}
  commands:
    # runs tests for package only, report only what is in the package
    # creates xml tests report and place it in a specific directory
    # creates html and xml coverage reports and place them in a specific directory
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: {{ data['project']['urls']['homepage'] }}
  license: {{ data['project']['description'] }}
  summary: {{ data['project']['license']['text'] }}
  license_family: BSD
