{% set name = 'bob.learn.em' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"
    # installs the documentation source, readme to share/doc so it is available
    # during test time
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst requirements.txt doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob.extension
    - bob.blitz
    - bob.io.base
    - bob.sp
    - bob.learn.activation
    - bob.learn.linear
    - numpy {{ numpy }}
    - dask {{ dask }}
    - dask-ml {{ dask_ml }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('dask') }}
    - {{ pin_compatible('dask-ml') }}

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - matplotlib {{ matplotlib }}
    - bob.db.iris

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Bindings for emelaneous machines and trainers of Bob
  license_family: BSD
