{% set data = load_file_data(RECIPE_DIR + '/../pyproject.toml') %}
{% set name = data['project']['name'] %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ data['project']['version'] }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    - "{{ PYTHON }} -m pip install . -vv"
    # installs the documentation source, readme to share/doc so it is available
    # during test time
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst requirements.txt doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob.extension
    - numpy {{ numpy }}
    - dask {{ dask }}
    - dask-ml {{ dask_ml }}
    - h5py {{ h5py }}
    - h5py >=3
    - scikit-learn {{ scikit_learn }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - {{ pin_compatible('dask') }}
    - {{ pin_compatible('dask-ml') }}
    - {{ pin_compatible('h5py') }}
    # scikit-learn keeps breaking API in minor versions, so we pin to the
    # next minor version
    - {{ pin_compatible('scikit-learn', max_pin='x.x') }}

test:
  imports:
    - {{ name }}
  commands:
    # runs tests for package only, report only what is in the package
    # creates xml tests report and place it in a specific directory
    # creates html and xml coverage reports and place them in a specific directory
    - ls -lah
    - pytest --verbose --cov {{ name }} --cov-report term-missing --cov-report html:{{ project_dir }}/sphinx/coverage --cov-report xml:{{ project_dir }}/coverage.xml --junitxml={{ project_dir }}/test_results.xml --pyargs {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - pytest {{ pytest }}
    - pytest-cov {{ pytest_cov }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - matplotlib {{ matplotlib }}

about:
  home: {{ data['project']['urls']['homepage'] }}
  license: {{ data['project']['description'] }}
  summary: {{ data['project']['license']['text'] }}
  license_family: BSD
